### ISSUE TITLE
simple example of postgres with ros2 bag contains custom messages

### ISSUE THREAD

**Issue by iftahnaf** [suurjaak/grepros#2]
hi,

great job with this project, amazing capabilities.

I haven't found in the docs any example for my simple case:

load my entire ros2 bag (.db3 file) to postgres.
my bag has some custom messages inside.

I tried with:
```
grepros -n test.db3 --write postgresql://ubuntu@localhost/test  --progress

```

Not sure where I should point to the ros message package.

Thanks in advance.

**Comment by suurjaak** [comment]
> great job with this project, amazing capabilities.

Thanks!

That command looks all correct. What is the result you are getting? 

The ROS2 message type Python packages need to be available in path, same as they would be if you ran a ROS2 node using these messages. Sourcing a built workspace should be sufficient.

**Comment by iftahnaf** [comment]
Hi,

I source the workspace and it worked, thanks!
